# Generated by Django 5.2.15 on 2026-06-23 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('source', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('catalog', 'Catálogo')], default='web', max_length=30, verbose_name='Origen')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Contactado'), ('closed', 'Cerrado')], default='new', max_length=30, verbose_name='Estado')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='catalog.product', verbose_name='Producto consultado')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='catalog.provider', verbose_name='Proveedor / Editorial')),
            ],
            options={
                'verbose_name': 'Solicitud de contacto',
                'verbose_name_plural': 'Solicitudes de contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
