# Generated by Django 5.2.15 on 2026-07-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Contactado'), ('in_follow_up', 'En seguimiento'), ('closed', 'Cerrado'), ('discarded', 'Descartado')], default='new', max_length=30, verbose_name='Estado'),
        ),
    ]
