# Generated by Django 5.2.15 on 2026-08-28 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_alter_contactrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_requests', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de atención'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='last_attention_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atención'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima acción'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nueva'), ('under_review', 'En revisión'), ('contacted', 'Contactado'), ('in_follow_up', 'En seguimiento'), ('closed', 'Cerrado'), ('discarded', 'Descartado')], default='new', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ContactRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('action_type', models.CharField(choices=[('general', 'Comentario general'), ('whatsapp', 'Contacto por WhatsApp'), ('phone', 'Llamada telefónica'), ('email', 'Correo electrónico'), ('follow_up', 'Seguimiento'), ('internal', 'Nota interna'), ('other', 'Otro')], default='general', max_length=30, verbose_name='Tipo de acción')),
                ('comment', models.TextField(verbose_name='Comentario / evidencia')),
                ('contact_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inquiries.contactrequest', verbose_name='Solicitud')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_request_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de solicitud',
                'verbose_name_plural': 'Comentarios de solicitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=30, verbose_name='Estado nuevo')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_request_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('contact_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inquiries.contactrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Historial de estado de solicitud',
                'verbose_name_plural': 'Historial de estados de solicitudes',
                'ordering': ['-created_at'],
            },
        ),
    ]
