# Generated by Django 5.2.15 on 2026-09-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_contactrequest_assigned_to_contactrequest_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'permissions': [('view_inquiries', 'Puede consultar solicitudes'), ('manage_inquiries', 'Puede gestionar solicitudes'), ('assign_inquiries', 'Puede asignar solicitudes')], 'verbose_name': 'Solicitud de contacto', 'verbose_name_plural': 'Solicitudes de contacto'},
        ),
    ]
