# Generated by Django 5.2.15 on 2026-08-31 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0003_contactrequest_assigned_to_contactrequest_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('meeting', 'Reunión'), ('call', 'Llamada'), ('visit', 'Visita'), ('training', 'Capacitación'), ('delivery', 'Entrega'), ('deadline', 'Fecha límite'), ('internal', 'Interno'), ('other', 'Otro')], default='meeting', max_length=30, verbose_name='Tipo de evento')),
                ('start_at', models.DateTimeField(verbose_name='Inicio')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Todo el día')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='Lugar')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('participants', models.ManyToManyField(blank=True, related_name='calendar_event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
                ('related_contact_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_calendar_events', to='inquiries.contactrequest', verbose_name='Solicitud relacionada')),
            ],
            options={
                'verbose_name': 'Evento de calendario',
                'verbose_name_plural': 'Eventos de calendario',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('task_type', models.CharField(choices=[('general', 'General'), ('customer_request', 'Solicitud de cliente'), ('catalog', 'Catálogo'), ('price', 'Precio'), ('publisher', 'Editorial / Proveedor'), ('reading_plan', 'Plan lector'), ('school', 'Colegio'), ('delivery', 'Entrega'), ('meeting', 'Reunión'), ('call', 'Llamada'), ('school_campaign', 'Campaña escolar'), ('administration', 'Administración'), ('warehouse', 'Almacén'), ('other', 'Otro')], default='general', max_length=40, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('waiting', 'En espera'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=30, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=30, verbose_name='Prioridad')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite')),
                ('reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('is_important', models.BooleanField(default=False, verbose_name='Importante')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privada')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('related_contact_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='inquiries.contactrequest', verbose_name='Solicitud relacionada')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['status', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('remind_at', models.DateTimeField(verbose_name='Fecha de recordatorio')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('seen', 'Visto'), ('dismissed', 'Descartado'), ('completed', 'Completado')], default='pending', max_length=30, verbose_name='Estado')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='workspaces.calendarevent', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='workspaces.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['remind_at'],
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='workspaces.task', verbose_name='Tarea relacionada'),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('comment', models.TextField(verbose_name='Comentario / evidencia')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workspaces.task', verbose_name='Tarea')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de tarea',
                'verbose_name_plural': 'Comentarios de tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=30, verbose_name='Estado nuevo')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='workspaces.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Historial de estado de tarea',
                'verbose_name_plural': 'Historial de estados de tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(blank=True, default='gray', max_length=30, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspace_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Grupo de trabajo',
                'verbose_name_plural': 'Grupos de trabajo',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspaces.workspacegroup', verbose_name='Grupo de trabajo'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='workspaces.workspacegroup', verbose_name='Grupo de trabajo'),
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('role', models.CharField(choices=[('owner', 'Responsable'), ('coordinator', 'Coordinador'), ('member', 'Miembro'), ('viewer', 'Observador')], default='member', max_length=30, verbose_name='Rol en el grupo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspacegroup', verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro de grupo',
                'verbose_name_plural': 'Miembros de grupos',
                'ordering': ['group__name', 'user__username'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
