# Generated by Django 5.2.15 on 2026-09-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_reminder_options_reminder_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Seguimiento de tarea', 'verbose_name_plural': 'Seguimientos de tareas'},
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='action_type',
            field=models.CharField(choices=[('comment', 'Comentario'), ('call', 'Llamada'), ('whatsapp', 'WhatsApp'), ('meeting', 'Reunión'), ('visit', 'Visita'), ('sample_delivery', 'Entrega de muestra'), ('presentation', 'Presentación'), ('evidence', 'Evidencia'), ('other', 'Otro')], default='comment', max_length=30, verbose_name='Tipo de seguimiento'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment',
            field=models.TextField(verbose_name='Detalle del seguimiento'),
        ),
    ]
