# Generated by Django 5.2.15 on 2026-09-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_taskcomment_options_taskcomment_action_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'due_at', '-created_at'], 'permissions': [('assign_work', 'Puede asignar trabajo a otros usuarios')], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='workspacegroup',
            options={'ordering': ['name'], 'permissions': [('use_workspace', 'Puede usar ToDo y Agenda'), ('create_workspace_group', 'Puede crear grupos de trabajo'), ('supervise_workspace', 'Puede supervisar trabajo')], 'verbose_name': 'Grupo de trabajo', 'verbose_name_plural': 'Grupos de trabajo'},
        ),
    ]
