# Generated by Django 5.2.15 on 2026-09-17 17:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_cargaexcel_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del equipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_teams', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Equipo comercial',
                'verbose_name_plural': 'Equipos comerciales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommercialTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('advisor', 'Asesor comercial'), ('support', 'Apoyo comercial')], default='advisor', max_length=20, verbose_name='Rol en el equipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('joined_on', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.commercialteam', verbose_name='Equipo comercial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro de equipo comercial',
                'verbose_name_plural': 'Miembros de equipos comerciales',
                'ordering': ['team__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(db_index=True, max_length=220, verbose_name='Nombre del colegio')),
                ('modular_code', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Código modular')),
                ('ruc', models.CharField(blank=True, db_index=True, max_length=11, verbose_name='RUC')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=250, verbose_name='Referencia')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('estimated_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alumnos estimados')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_schools', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('levels', models.ManyToManyField(blank=True, related_name='crm_schools', to='catalog.level', verbose_name='Niveles educativos')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_owned_schools', to=settings.AUTH_USER_MODEL, verbose_name='Asesor responsable')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='crm.commercialteam', verbose_name='Equipo comercial')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('full_name', models.CharField(max_length=180, verbose_name='Nombre completo')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Cargo / función')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contacto principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_school_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.school', verbose_name='Colegio')),
            ],
            options={
                'verbose_name': 'Contacto de colegio',
                'verbose_name_plural': 'Contactos de colegios',
                'ordering': ['school__name', '-is_primary', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Año')),
                ('campaign_type', models.CharField(choices=[('school', 'Campaña escolar'), ('reading_plan', 'Plan lector'), ('general', 'General')], default='school', max_length=30, verbose_name='Tipo de campaña')),
                ('status', models.CharField(choices=[('planning', 'Planificación'), ('active', 'Activa'), ('closed', 'Cerrada')], default='planning', max_length=20, verbose_name='Estado')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Campaña comercial',
                'verbose_name_plural': 'Campañas comerciales',
                'ordering': ['-year', 'name'],
                'permissions': [('view_crm', 'Puede consultar el CRM'), ('manage_campaigns', 'Puede gestionar campañas del CRM'), ('manage_commercial_teams', 'Puede gestionar equipos comerciales'), ('manage_schools', 'Puede gestionar colegios y contactos'), ('assign_schools', 'Puede asignar colegios a asesores'), ('manage_own_opportunities', 'Puede gestionar sus oportunidades'), ('assign_opportunities', 'Puede asignar oportunidades'), ('supervise_crm', 'Puede supervisar el CRM comercial'), ('manage_quotations', 'Puede gestionar cotizaciones'), ('manage_adoptions', 'Puede gestionar adopciones'), ('export_crm_reports', 'Puede exportar reportes del CRM')],
                'indexes': [models.Index(fields=['year', 'status'], name='crm_cmp_year_status_idx'), models.Index(fields=['campaign_type', 'status'], name='crm_cmp_type_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='crm_cmp_valid_dates')],
            },
        ),
        migrations.AddIndex(
            model_name='commercialteam',
            index=models.Index(fields=['is_active', 'name'], name='crm_team_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialteammembership',
            index=models.Index(fields=['user', 'is_active'], name='crm_team_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialteammembership',
            index=models.Index(fields=['team', 'role', 'is_active'], name='crm_team_role_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialteammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='crm_team_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='commercialteammembership',
            constraint=models.CheckConstraint(condition=models.Q(('joined_on__isnull', True), ('ended_on__isnull', True), ('ended_on__gte', models.F('joined_on')), _connector='OR'), name='crm_team_valid_dates'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active', 'name'], name='crm_school_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['owner', 'is_active'], name='crm_school_owner_active_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['team', 'is_active'], name='crm_school_team_active_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['department', 'province', 'district'], name='crm_school_location_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolcontact',
            index=models.Index(fields=['school', 'is_active'], name='crm_contact_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolcontact',
            index=models.Index(fields=['school', 'is_primary'], name='crm_contact_school_main_idx'),
        ),
    ]
