# Generated by Django 5.2.15 on 2026-09-17 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_default', models.BooleanField(default=False, verbose_name='Pipeline predeterminado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_pipelines', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Pipeline comercial',
                'verbose_name_plural': 'Pipelines comerciales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Oportunidad')),
                ('notes', models.TextField(blank=True, verbose_name='Resumen / observaciones')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('closure_note', models.TextField(blank=True, verbose_name='Motivo / detalle de cierre')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.campaign', verbose_name='Campaña')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_crm_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_owned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Asesor responsable')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_opportunities', to='crm.schoolcontact', verbose_name='Contacto principal')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.school', verbose_name='Colegio')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.commercialteam', verbose_name='Equipo comercial')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Oportunidad comercial',
                'verbose_name_plural': 'Oportunidades comerciales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.CharField(max_length=60, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Orden')),
                ('category', models.CharField(choices=[('open', 'Abierta'), ('won', 'Ganada'), ('lost', 'No concretada')], default='open', max_length=10, verbose_name='Categoría')),
                ('is_initial', models.BooleanField(default=False, verbose_name='Etapa inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_pipeline_stages', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Etapa del pipeline',
                'verbose_name_plural': 'Etapas del pipeline',
                'ordering': ['pipeline__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('transition_type', models.CharField(choices=[('created', 'Creación'), ('stage_change', 'Cambio de etapa'), ('reopened', 'Reapertura')], default='stage_change', max_length=20, verbose_name='Tipo de transición')),
                ('note', models.TextField(blank=True, verbose_name='Motivo / observación')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunity_stage_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='crm.opportunity', verbose_name='Oportunidad')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_transitions_from', to='crm.pipelinestage', verbose_name='Etapa anterior')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_transitions_to', to='crm.pipelinestage', verbose_name='Nueva etapa')),
            ],
            options={
                'verbose_name': 'Historial de etapa',
                'verbose_name_plural': 'Historial de etapas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.pipelinestage', verbose_name='Etapa actual'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['is_active', 'name'], name='crm_pipe_active_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='crm_pipeline_one_default'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['pipeline', 'is_active', 'order'], name='crm_stage_pipe_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['pipeline', 'category'], name='crm_stage_pipe_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'code'), name='crm_stage_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'order'), name='crm_stage_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('pipeline',), name='crm_stage_one_initial'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.CheckConstraint(condition=models.Q(('is_initial', False), ('category', 'open'), _connector='OR'), name='crm_stage_initial_open'),
        ),
        migrations.AddIndex(
            model_name='opportunitystagehistory',
            index=models.Index(fields=['opportunity', '-created_at'], name='crm_opp_hist_date_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['campaign', 'stage'], name='crm_opp_cmp_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner', 'stage'], name='crm_opp_owner_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['team', 'stage'], name='crm_opp_team_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['school', 'campaign'], name='crm_opp_school_cmp_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['closed_at'], name='crm_opp_closed_idx'),
        ),
    ]
