# Generated by Django 5.2.15 on 2026-09-17 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_pipeline_opportunity_pipelinestage_and_more'),
        ('workspaces', '0004_alter_task_options_alter_workspacegroup_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Última actividad comercial'),
        ),
        migrations.CreateModel(
            name='CommercialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activity_type', models.CharField(choices=[('call', 'Llamada'), ('whatsapp', 'WhatsApp'), ('email', 'Correo'), ('meeting', 'Reunión'), ('visit', 'Visita'), ('presentation', 'Presentación'), ('sample_delivery', 'Entrega de muestra'), ('sample_return', 'Devolución de muestra'), ('follow_up', 'Seguimiento'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de actividad')),
                ('summary', models.CharField(max_length=200, verbose_name='Resumen')),
                ('result', models.TextField(verbose_name='Resultado / detalle')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la actividad')),
                ('is_important', models.BooleanField(default=False, verbose_name='Importante')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_activities', to='crm.schoolcontact', verbose_name='Contacto del colegio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_activities', to='crm.opportunity', verbose_name='Oportunidad')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Actividad comercial',
                'verbose_name_plural': 'Actividades comerciales',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CRMWorkItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_work_item_links', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_links', to='workspaces.calendarevent', verbose_name='Evento')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_links', to='crm.opportunity', verbose_name='Oportunidad')),
                ('origin_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_work_item_links', to='crm.commercialactivity', verbose_name='Actividad de origen')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_links', to='workspaces.reminder', verbose_name='Recordatorio')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_links', to='workspaces.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Vínculo CRM / trabajo',
                'verbose_name_plural': 'Vínculos CRM / trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commercialactivity',
            index=models.Index(fields=['opportunity', '-occurred_at'], name='crm_act_opp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialactivity',
            index=models.Index(fields=['performed_by', '-occurred_at'], name='crm_act_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialactivity',
            index=models.Index(fields=['activity_type', '-occurred_at'], name='crm_act_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='crmworkitemlink',
            index=models.Index(fields=['opportunity', '-created_at'], name='crm_work_opp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='crmworkitemlink',
            index=models.Index(fields=['origin_activity', '-created_at'], name='crm_work_act_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmworkitemlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task__isnull', False), ('event__isnull', True), ('reminder__isnull', True)), models.Q(('task__isnull', True), ('event__isnull', False), ('reminder__isnull', True)), models.Q(('task__isnull', True), ('event__isnull', True), ('reminder__isnull', False)), _connector='OR'), name='crm_work_exactly_one_item'),
        ),
        migrations.AddConstraint(
            model_name='crmworkitemlink',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('task',), name='crm_work_unique_task'),
        ),
        migrations.AddConstraint(
            model_name='crmworkitemlink',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event',), name='crm_work_unique_event'),
        ),
        migrations.AddConstraint(
            model_name='crmworkitemlink',
            constraint=models.UniqueConstraint(condition=models.Q(('reminder__isnull', False)), fields=('reminder',), name='crm_work_unique_reminder'),
        ),
    ]
