# Generated by Django 5.2.15 on 2026-09-19 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cargaexcel_options_alter_product_options_and_more'),
        ('crm', '0003_opportunity_last_activity_at_commercialactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCommercialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('population_total', models.PositiveIntegerField(default=0, verbose_name='Población total considerada')),
                ('segment', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('OUT', 'Fuera del objetivo base')], default='OUT', max_length=10, verbose_name='Segmento')),
                ('textbook_usage', models.CharField(choices=[('unknown', 'Sin información'), ('core', 'Utiliza textos principales'), ('complementary', 'Solo áreas complementarias'), ('none', 'No utiliza textos escolares')], default='unknown', max_length=30, verbose_name='Uso de textos')),
                ('priority_score', models.PositiveSmallIntegerField(default=0, verbose_name='Puntaje de prioridad')),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja'), ('undefined', 'Sin evaluar')], default='undefined', max_length=20, verbose_name='Prioridad comercial')),
                ('score_reasons', models.JSONField(blank=True, default=list, verbose_name='Factores del puntaje')),
                ('score_version', models.CharField(default='v1', max_length=30, verbose_name='Versión del cálculo')),
                ('scored_at', models.DateTimeField(blank=True, null=True, verbose_name='Último cálculo')),
            ],
            options={
                'verbose_name': 'Perfil comercial de colegio',
                'verbose_name_plural': 'Perfiles comerciales de colegios',
                'ordering': ['-campaign__year', 'school__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEditorialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Año')),
                ('status', models.CharField(choices=[('current', 'Uso actual'), ('previous', 'Uso anterior'), ('reported', 'Información por confirmar')], default='reported', max_length=20, verbose_name='Estado de información')),
                ('source', models.CharField(choices=[('minedu', 'MINEDU'), ('import', 'Importación'), ('advisor', 'Asesor comercial'), ('management', 'Jefatura comercial'), ('manual', 'Registro manual'), ('other', 'Otro')], default='manual', max_length=30, verbose_name='Fuente')),
                ('observed_on', models.DateField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Uso editorial del colegio',
                'verbose_name_plural': 'Usos editoriales de colegios',
                'ordering': ['school__name', '-year', 'area__name', 'provider__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEducationalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('modular_code', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Código modular')),
                ('modality', models.CharField(blank=True, max_length=100, verbose_name='Modalidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio educativo',
                'verbose_name_plural': 'Servicios educativos',
                'ordering': ['school__name', 'level__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolPopulationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Año')),
                ('student_count', models.PositiveIntegerField(verbose_name='Cantidad de alumnos')),
                ('source', models.CharField(choices=[('minedu', 'MINEDU'), ('import', 'Importación'), ('advisor', 'Asesor comercial'), ('management', 'Jefatura comercial'), ('manual', 'Registro manual'), ('other', 'Otro')], default='manual', max_length=30, verbose_name='Fuente')),
                ('source_detail', models.CharField(blank=True, max_length=250, verbose_name='Detalle de la fuente')),
                ('is_current', models.BooleanField(default=True, verbose_name='Dato vigente')),
            ],
            options={
                'verbose_name': 'Población de colegio',
                'verbose_name_plural': 'Historial de población de colegios',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='institution_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Código de institución'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(condition=models.Q(('institution_code__isnull', False)), fields=('institution_code',), name='crm_school_unique_institution_code'),
        ),
        migrations.AddField(
            model_name='schoolcommercialprofile',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_commercial_profiles', to='crm.campaign', verbose_name='Campaña'),
        ),
        migrations.AddField(
            model_name='schoolcommercialprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profiles', to='crm.school', verbose_name='Colegio'),
        ),
        migrations.AddField(
            model_name='schooleditorialusage',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_school_editorial_usages', to='catalog.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='schooleditorialusage',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_school_usages', to='catalog.provider', verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='schooleditorialusage',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_crm_editorial_usages', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='schooleditorialusage',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_usages', to='crm.school', verbose_name='Colegio'),
        ),
        migrations.AddField(
            model_name='schooleducationalservice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_services', to='crm.school', verbose_name='Colegio'),
        ),
        migrations.AddField(
            model_name='schooleducationalservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_school_services', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='schooleducationalservice',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_school_services', to='catalog.level', verbose_name='Nivel educativo'),
        ),
        migrations.AddField(
            model_name='schooleditorialusage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_usages', to='crm.schooleducationalservice', verbose_name='Servicio educativo'),
        ),
        migrations.AddField(
            model_name='schoolpopulationrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_crm_school_populations', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='schoolpopulationrecord',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_records', to='crm.schooleducationalservice', verbose_name='Servicio educativo'),
        ),
        migrations.AddIndex(
            model_name='schoolcommercialprofile',
            index=models.Index(fields=['campaign', 'segment'], name='crm_profile_segment_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolcommercialprofile',
            index=models.Index(fields=['campaign', 'priority'], name='crm_profile_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolcommercialprofile',
            constraint=models.UniqueConstraint(fields=('school', 'campaign'), name='crm_unique_school_campaign_profile'),
        ),
        migrations.AddIndex(
            model_name='schooleducationalservice',
            index=models.Index(fields=['school', 'is_active'], name='crm_service_school_active_idx'),
        ),
        migrations.AddIndex(
            model_name='schooleducationalservice',
            index=models.Index(fields=['level', 'is_active'], name='crm_service_level_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='schooleducationalservice',
            constraint=models.UniqueConstraint(condition=models.Q(('modular_code__isnull', False)), fields=('modular_code',), name='crm_service_unique_modular_code'),
        ),
        migrations.AddIndex(
            model_name='schooleditorialusage',
            index=models.Index(fields=['school', 'year'], name='crm_usage_school_year_idx'),
        ),
        migrations.AddIndex(
            model_name='schooleditorialusage',
            index=models.Index(fields=['provider', 'year'], name='crm_usage_provider_year_idx'),
        ),
        migrations.AddIndex(
            model_name='schooleditorialusage',
            index=models.Index(fields=['status', 'year'], name='crm_usage_status_year_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolpopulationrecord',
            index=models.Index(fields=['service', 'year', 'is_current'], name='crm_population_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolpopulationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('service', 'year'), name='crm_population_one_current'),
        ),
    ]
