# Generated by Django 5.2.15 on 2026-09-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_school_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooleducationalservice',
            options={'ordering': ['school__name', 'level__name'], 'verbose_name': 'Servicio educativo', 'verbose_name_plural': 'Servicios educativos'},
        ),
    ]
