# Generated by Django 5.2.15 on 2026-09-20 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cargaexcel_options_alter_product_options_and_more'),
        ('crm', '0006_alter_schooleducationalservice_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schooleducationalservice',
            constraint=models.UniqueConstraint(fields=('school', 'level'), name='crm_service_unique_school_level'),
        ),
    ]
