# Generated by Django 5.2.15 on 2026-09-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_schooleducationalservice_crm_service_unique_school_level'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schoolpopulationrecord',
            name='crm_population_one_current',
        ),
    ]
