# Generated by Django 5.2.15 on 2026-09-20 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_schoolpopulationrecord_crm_population_one_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schoolpopulationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('service',), name='crm_population_one_current'),
        ),
    ]
