# Generated by Django 5.2.15 on 2026-09-21 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cargaexcel_options_alter_product_options_and_more'),
        ('crm', '0009_schoolpopulationrecord_crm_population_one_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=180, verbose_name='Editorial')),
                ('normalized_name', models.CharField(editable=False, max_length=220, unique=True, verbose_name='Nombre normalizado')),
                ('verification_status', models.CharField(choices=[('pending', 'Pendiente de validación'), ('verified', 'Validada')], default='pending', max_length=20, verbose_name='Estado de validación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('catalog_provider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_market_editorial', to='catalog.provider', verbose_name='Editorial vinculada al catálogo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_market_editorials', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Editorial del mercado',
                'verbose_name_plural': 'Editoriales del mercado',
                'ordering': ['name'],
            },
        ),
    ]
