# Generated by Django 5.2.15 on 2026-09-21 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_marketeditorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooleditorialusage',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_usages', to='crm.marketeditorial', verbose_name='Editorial'),
        ),
    ]
