# Generated by Django 5.2.15 on 2026-09-21 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cargaexcel_options_alter_product_options_and_more'),
        ('crm', '0012_migrate_market_editorials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooleditorialusage',
            options={'ordering': ['school__name', '-year', 'area__name', 'editorial__name'], 'verbose_name': 'Uso editorial del colegio', 'verbose_name_plural': 'Usos editoriales de colegios'},
        ),
        migrations.AlterField(
            model_name='schooleditorialusage',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_school_usages', to='catalog.provider', verbose_name='Editorial del catálogo'),
        ),
    ]
