# Generated by Django 5.2.15 on 2026-09-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_schooleditorialusage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooleditorialusage',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Producto / serie observada'),
        ),
    ]
