# Generated by Django 5.2.15 on 2026-09-23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0004_alter_cargaexcel_options_alter_product_options_and_more",
        ),
        ("crm", "0016_school_activity_work_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolPopulationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Fecha de actualización",
                    ),
                ),
                (
                    "section_count",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Número de secciones",
                    ),
                ),
                (
                    "students_per_section",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Alumnos por sección",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crm_school_population_details",
                        to="catalog.grade",
                        verbose_name="Grado",
                    ),
                ),
                (
                    "population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="crm.schoolpopulationrecord",
                        verbose_name="Registro de población",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de población por grado",
                "verbose_name_plural": (
                    "Detalles de población por grado"
                ),
                "ordering": ["grade__order", "grade__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="schoolpopulationdetail",
            constraint=models.UniqueConstraint(
                fields=("population", "grade"),
                name="crm_population_unique_grade",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolpopulationdetail",
            index=models.Index(
                fields=["population", "grade"],
                name="crm_population_grade_idx",
            ),
        ),
    ]
