# Generated by Django 5.2.15 on 2026-10-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0031_fair_end_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="dependency",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="Dependencia",
            ),
        ),
        migrations.CreateModel(
            name="SchoolImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Fecha de actualización",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="crm/importaciones/colegios/",
                        verbose_name="Archivo Excel",
                    ),
                ),
                (
                    "population_year",
                    models.PositiveIntegerField(
                        verbose_name="Año de población",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        default="Instituciones",
                        max_length=120,
                        verbose_name="Hoja",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("validated", "Validado"),
                            ("imported", "Importado"),
                            ("error", "Con errores"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_schools",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_new",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_updated",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_errors",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_crm_school_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importación de colegios",
                "verbose_name_plural": "Importaciones de colegios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Fecha de actualización",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        verbose_name="Fila del Excel",
                    ),
                ),
                (
                    "institution_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="Código de institución",
                    ),
                ),
                (
                    "modular_code",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Código modular",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        max_length=220,
                        verbose_name="Nombre del colegio",
                    ),
                ),
                (
                    "level_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Nivel / modalidad",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("update", "Actualizar"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Datos de la fila",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        verbose_name="Procesado",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="crm.schoolimportbatch",
                        verbose_name="Importación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila de importación de colegios",
                "verbose_name_plural": "Filas de importación de colegios",
                "ordering": ["row_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"),
                        name="crm_school_import_unique_row",
                    ),
                ],
            },
        ),
    ]
