# Generated by Django 5.2.15 on 2026-06-23 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Área')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Grado')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nivel')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo de producto')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de producto',
                'verbose_name_plural': 'Tipos de producto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre comercial')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Razón social')),
                ('ruc', models.CharField(blank=True, max_length=20, verbose_name='RUC')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='providers/logos/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Proveedor / Editorial',
                'verbose_name_plural': 'Proveedores / Editoriales',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=150, verbose_name='Serie')),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='catalog.provider', verbose_name='Proveedor / Editorial')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del libro')),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='Código interno / SKU')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/covers/', verbose_name='Portada')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.area', verbose_name='Área')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.grade', verbose_name='Grado')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.level', verbose_name='Nivel')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.producttype', verbose_name='Tipo de producto')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.provider', verbose_name='Proveedor / Editorial')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.series', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Producto / Libro',
                'verbose_name_plural': 'Productos / Libros',
                'ordering': ['provider__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('year', models.PositiveIntegerField(verbose_name='Año de catálogo')),
                ('campaign', models.CharField(default='Campaña escolar', max_length=100, verbose_name='Campaña')),
                ('currency', models.CharField(default='PEN', max_length=10, verbose_name='Moneda')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio referencial')),
                ('show_price', models.BooleanField(default=False, verbose_name='Mostrar precio en web')),
                ('consult_price', models.BooleanField(default=True, verbose_name='Mostrar como consultar precio')),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('limited', 'Stock limitado'), ('out_of_stock', 'Agotado'), ('on_request', 'A consultar')], default='on_request', max_length=30, verbose_name='Disponibilidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Precio por año',
                'verbose_name_plural': 'Precios por año',
                'ordering': ['-year', 'product__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'year', 'campaign'), name='unique_price_by_product_year_campaign')],
            },
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='unique_series_by_provider'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='unique_product_name_by_provider'),
        ),
    ]
