# Generated by Django 5.2.15 on 2026-06-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/productos/')),
                ('anio_catalogo', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('IMPORTADO', 'Importado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('total_nuevos', models.PositiveIntegerField(default=0)),
                ('total_actualizados', models.PositiveIntegerField(default=0)),
                ('total_errores', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carga Excel',
                'verbose_name_plural': 'Cargas Excel',
            },
        ),
        migrations.CreateModel(
            name='CargaExcelDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.PositiveIntegerField()),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor_editorial', models.CharField(blank=True, max_length=150, null=True)),
                ('accion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('ACTUALIZAR', 'Actualizar'), ('ERROR', 'Error')], max_length=20)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('datos_originales', models.JSONField(blank=True, default=dict)),
                ('procesado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='catalog.cargaexcel')),
            ],
            options={
                'verbose_name': 'Detalle de carga Excel',
                'verbose_name_plural': 'Detalles de carga Excel',
            },
        ),
    ]
