# Generated by Django 5.2.15 on 2026-06-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cargaexcel_cargaexceldetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de producto / código de barras'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio costo'),
        ),
    ]
