# Generated by Django 5.2.15 on 2026-09-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_code_productprice_cost_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargaexcel',
            options={'permissions': [('manage_imports', 'Puede gestionar importaciones de catálogo')], 'verbose_name': 'Carga Excel', 'verbose_name_plural': 'Cargas Excel'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['provider__name', 'order', 'name'], 'permissions': [('view_catalog', 'Puede consultar el catálogo interno'), ('manage_catalog', 'Puede gestionar el catálogo')], 'verbose_name': 'Producto / Libro', 'verbose_name_plural': 'Productos / Libros'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['-year', 'product__name'], 'permissions': [('view_prices', 'Puede consultar precios internos'), ('manage_prices', 'Puede gestionar precios')], 'verbose_name': 'Precio por año', 'verbose_name_plural': 'Precios por año'},
        ),
    ]
