# Generated by Django 5.2.15 on 2026-09-15 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='Tipo de evento')),
                ('module', models.CharField(db_index=True, max_length=60, verbose_name='Módulo')),
                ('severity', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error')], db_index=True, default='info', max_length=20, verbose_name='Severidad')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Enlace interno')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('source_app', models.CharField(blank=True, max_length=80, verbose_name='Aplicación origen')),
                ('source_model', models.CharField(blank=True, max_length=80, verbose_name='Modelo origen')),
                ('source_id', models.CharField(blank=True, max_length=80, verbose_name='Identificador origen')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('dedup_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave de deduplicación')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Generada por')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_rec_read_created_idx'), models.Index(fields=['recipient', 'module', '-created_at'], name='notif_rec_module_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedup_key'), name='unique_notification_dedup_per_recipient')],
            },
        ),
    ]
